version: "3"
services:
  rds:
    image: "postgres:12-alpine"
    container_name: rds
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    networks:
      intranet:

  web:
    restart: on-failure
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DB_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@rds:5432/postgres
    env_file:
      - .env
    volumes:
      - "./migrations:/app/migrations"
    networks:
      intranet:
    depends_on:
      - rds
networks:
  intranet: